### ISSUE TITLE
Build breaking in NodeToolInstaller

### ISSUE THREAD

**Issue by rahul-chaudhary** [forcedotcom/aura#126]
Build failing on Windows PC when building aura-module. error message is 
`<code>
SEVERE: [node-tool] NodeToolInstaller: SHOW_IN_NT_ERRORS: error installing node-envjava.lang.Class: java.io.FileNotFoundException: C:\Users\Rahul%20Chaudhary\.m2\repository\org\auraframework\node-tool\0.0.15\node-tool-0.0.15.jar (The system cannot find the path specified)
Exception in thread "main" java.lang.Error: error installing node-envjava.lang.Class: java.io.FileNotFoundException: C:\Users\Rahul%20Chaudhary\.m2\repository\org\auraframework\node-tool\0.0.15\node-tool-0.0.15.jar (The system cannot find the path specified)
        at org.auraframework.tools.node.NodeToolInstaller.installIfMissing(NodeToolInstaller.java:107)
        at org.auraframework.tools.node.NodeToolInstaller.<clinit>(NodeToolInstaller.java:37)
        at org.auraframework.modules.impl.ModulesCompilerNode.getCompileFunction(ModulesCompilerNode.java:41)
        at org.auraframework.modules.impl.ModulesCompilerNode.compile(ModulesCompilerNode.java:51)
        at org.auraframework.modules.impl.ModulesCompilerServiceImpl.compile(ModulesCompilerServiceImpl.java:42)
        at org.auraframework.modules.impl.factory.BundleModuleDefFactory.getDefinition(BundleModuleDefFactory.java:148)
        at org.auraframework.modules.impl.factory.BundleModuleDefFactory.getDefinition(BundleModuleDefFactory.java:55)
        at org.auraframework.impl.service.CompilerServiceImpl.getDefinitionTypeSafe(CompilerServiceImpl.java:82)
        at org.auraframework.impl.service.CompilerServiceImpl.compile(CompilerServiceImpl.java:105)
        at org.auraframework.impl.system.CompilingDefRegistry.getDef(CompilingDefRegistry.java:99)
        at org.auraframework.tools.definition.RegistrySerializer.getRegistry(RegistrySerializer.java:303)
        at org.auraframework.tools.definition.RegistrySerializer.write(RegistrySerializer.java:244)
        at org.auraframework.tools.definition.RegistrySerializer.execute(RegistrySerializer.java:393)
        at org.auraframework.tools.definition.AuraCompiler.main(AuraCompiler.java:158)
Caused by: java.io.FileNotFoundException: C:\Users\Rahul%20Chaudhary\.m2\repository\org\auraframework\node-tool\0.0.15\node-tool-0.0.15.jar (The system cannot find the path specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.auraframework.tools.node.util.ZipUtil.extractEntryFromJar(ZipUtil.java:19)
        at org.auraframework.tools.node.NodeToolInstaller.unzipIfMissing(NodeToolInstaller.java:135)
        at org.auraframework.tools.node.NodeToolInstaller.installIfMissing(NodeToolInstaller.java:96)
        ... 13 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
</code>`

**Comment by rahul-chaudhary** [comment]
Build related issues are fixed on Windows platform? I am not sure. I am anyway moved to Linux so its working out just fine for me. But i guess it is still not a very platform independent build
