### ISSUE TITLE
README - How Do I Start?  mvn clean install test failures

### ISSUE THREAD

**Issue by pjuneauGO** [forcedotcom/aura#161]
Steps 
OS: WINDOWS 10
Attempt Step 1 of How Do I Start?
1. Install JDK 1.8
2. Define JDK in JAVA_HOME variable
3. install Apache Maven 3
4. Define bin directory in PATH
5. run mvn -v to verify:
![image](https://user-images.githubusercontent.com/24941521/39100663-0f5ba80c-4642-11e8-96d2-b34854d107c3.png)
6. clone aura framework to C:/
7. run command:   mvn clean install
8. Test results produce following:
![image](https://user-images.githubusercontent.com/24941521/39100710-ca97aad0-4642-11e8-8620-30f3b266212d.png)

Step 2 cannot execute and is theorized to not work due to test failures identified in Step 1.
Entering, '1', for archetype is not recognized.  This is the point of failure.

**Comment by rahul-chaudhary** [comment]
1. Try to solve the problem causing the test failure
2. Configure the maven surefire plugin to set skipTests as true so that build can complete and you can create a startup project
3. Build on Nix like OS where build is working fine. Build have issues on windows os

**Comment by PhilippCl** [comment]
I tried what @rahul-chaudhary suggested. Still not working. On my Ubuntu Machine I get the following error: 
```
DEBUG: ENTRY: markup://module:marker@COMPONENT
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (compile-modules) @ aura-modules ---
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/home/phil/.m2/repository/org/springframework/spring-core/4.3.6.RELEASE/spring-core-4.3.6.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
iNFO: skipping: /home/phil/aura/aura-components/src/main/components
DEBUG: ******************************************* module ******************************
DEBUG: ENTRY: markup://module:marker@MODULE
Apr 23, 2018 9:32:19 AM org.auraframework.tools.node.impl.util.Log log
INFO: [node-tool] NodeToolProperties: loaded {node.version=v8.5.0, project.artifactId=node-tool, pom.version=0.1.7} in os.name:Linux,os.version:4.13.0-21-generic,os.arch:amd64
[node-tool] NodeToolProperties: loaded {node.version=v8.5.0, project.artifactId=node-tool, pom.version=0.1.7} in os.name:Linux,os.version:4.13.0-21-generic,os.arch:amd64
Apr 23, 2018 9:32:19 AM org.auraframework.tools.node.impl.util.Log log
INFO: [node-tool] NodeBundle: running from jar, bundleId=node-tool/0.1.7, projectJar=/home/phil/.m2/repository/org/auraframework/node-tool/0.1.7/node-tool-0.1.7.jar, urlFile=file:/home/phil/.m2/repository/org/auraframework/node-tool/0.1.7/node-tool-0.1.7.jar!/org/auraframework/tools/node/impl/NodeTool.class
[node-tool] NodeBundle: running from jar, bundleId=node-tool/0.1.7, projectJar=/home/phil/.m2/repository/org/auraframework/node-tool/0.1.7/node-tool-0.1.7.jar, urlFile=file:/home/phil/.m2/repository/org/auraframework/node-tool/0.1.7/node-tool-0.1.7.jar!/org/auraframework/tools/node/impl/NodeTool.class
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
    at org.auraframework.tools.node.impl.NodeBundleBuilder.build(NodeBundleBuilder.java:66)
    at org.auraframework.modules.impl.ModulesCompilerUtil.createCompilerBundle(ModulesCompilerUtil.java:79)
    at org.auraframework.modules.impl.ModulesCompilerUtil.getCompilerBundle(ModulesCompilerUtil.java:56)
    at org.auraframework.modules.impl.ModulesCompilerNode.getCompileLambda(ModulesCompilerNode.java:74)
    at org.auraframework.modules.impl.ModulesCompilerNode.compile(ModulesCompilerNode.java:44)
    at org.auraframework.modules.impl.ModulesCompilerServiceImpl.compile(ModulesCompilerServiceImpl.java:53)
    at org.auraframework.modules.impl.factory.BundleModuleDefFactory.getDefinition(BundleModuleDefFactory.java:147)
    at org.auraframework.modules.impl.factory.BundleModuleDefFactory.getDefinition(BundleModuleDefFactory.java:58)
    at org.auraframework.impl.service.CompilerServiceImpl.getDefinitionTypeSafe(CompilerServiceImpl.java:82)
    at org.auraframework.impl.service.CompilerServiceImpl.compile(CompilerServiceImpl.java:105)
    at org.auraframework.impl.system.CompilingDefRegistry.getDef(CompilingDefRegistry.java:101)
    at org.auraframework.tools.definition.RegistrySerializer.getRegistry(RegistrySerializer.java:303)
    at org.auraframework.tools.definition.RegistrySerializer.write(RegistrySerializer.java:243)
    at org.auraframework.tools.definition.RegistrySerializer.execute(RegistrySerializer.java:417)
    at org.auraframework.tools.definition.AuraCompiler.main(AuraCompiler.java:158)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
    ... 15 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Aura Framework ..................................... SUCCESS [  8.037 s]
[INFO] aura-interfaces .................................... SUCCESS [  6.369 s]
[INFO] aura-spring ........................................ SUCCESS [  2.587 s]
[INFO] aura-util .......................................... SUCCESS [ 13.874 s]
[INFO] aura ............................................... SUCCESS [ 45.618 s]
[INFO] aura-impl-expression ............................... SUCCESS [ 36.887 s]
[INFO] aura-impl .......................................... SUCCESS [01:41 min]
[INFO] aura-tools ......................................... SUCCESS [  1.827 s]
[INFO] aura-components .................................... SUCCESS [06:00 min]
[INFO] aura-modules ....................................... FAILURE [ 25.712 s]
[INFO] aura-resources ..................................... SKIPPED
[INFO] aura-integration-test .............................. SKIPPED
[INFO] aura-jetty ......................................... SKIPPED
[INFO] archetype for Aura-based "hello, world" ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:04 min
[INFO] Finished at: 2018-04-23T09:32:20+02:00
[INFO] Final Memory: 50M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (compile-modules) on project aura-modules: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aura-modules
```

As I listed in the issue i opened #160

**Comment by rahul-chaudhary** [comment]
Please pull updated code from upstream and try again. I am able to build successfully. please let us know your result in case you still face this problem.

**Comment by pjuneauGO** [comment]
Hi @rahul-chaudhary 

I was able to do the _mvn clean install_ and build the helloWorld project on a Mac I borrowed.

I have not tried on another UNIX operating system like Ubuntu.

On my Windows 10 machine, I pulled the latest code and retried.  I am still encountering the same errors though.

**Comment by clvinning** [comment]
Hello, despite what others have commented, I don't believe this to be an environment/OS specific problem. If you inspect _why_ it is failing, you'll see that a ClassNotFoundException is being thrown. This means that a resource the framework depends on is missing, and when the project build attempts to fetch it and finds that there is a whole lot of nope, things tend to blow up.

The resource missing is javax.xml.bind.DatatypeConverter, a quick google search reveals that this package is not intrinsically included in all JDK's. There are a couple of different approaches to resolving this. You can download the required Java EE modules and further configure your (extended) Java environment on your OS, or you can include them in the maven's dependency-managing POM file. Thankfully, there is a repository for all of this very useful information. For example, the link below will take you to the page I think will be able to resolve your particular problem. Click the link to one of the versions that are compatible with your JDK, and copy and paste the POM reference into your project's POM file and try to build again. If you are not familiar with maven and wish to explore maven projects such as this one and many others, I recommend reading maven's documentation at https://maven.apache.org/ to learn more about how it works! Knowledge is power! Good luck!

https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api

**Comment by dobias** [comment]
Please note that the maven-surefire plugin is configured to use the value of the 'skipUnitTests' property to to set the surefire skipTests property. **So use -DskipUnitTests=true** on the command line to skip the tests.
![image](https://user-images.githubusercontent.com/2144760/42776588-c0d04664-8937-11e8-92d3-54bcb7134a9a.png)

**Comment by rahul-chaudhary** [comment]
mvn clean install -DskipTests=true

**Comment by rajavardhan2geek** [comment]
@rahul-chaudhary 
Hi Rahul 
I am facing 
Aura Framework .................................... SUCCESS [9.659s]
[INFO] aura-interfaces ................................... SUCCESS [2.033s]
[INFO] aura-spring ....................................... SUCCESS [0.581s]
[INFO] aura-util ......................................... SUCCESS [19.443s]
[INFO] aura .............................................. SUCCESS [13.662s]
[INFO] aura-impl-expression .............................. SUCCESS [6.502s]
[INFO] aura-impl ......................................... FAILURE [1:11.701s]
[INFO] aura-tools ........................................ SKIPPED
[INFO] aura-components ................................... SKIPPED
[INFO] aura-modules ...................................... SKIPPED
[INFO] aura-resources .................................... SKIPPED
[INFO] aura-integration-test ............................. SKIPPED
[INFO] aura-jetty ........................................ SKIPPED
[INFO] archetype for Aura-based "hello, world" ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:04.153s
[INFO] Finished at: Sat Dec 01 01:46:46 IST 2018
[INFO] Final Memory: 25M/341M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (npm install (initialize)) on project aura-impl: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aura-impl

in building aura framework
