### ISSUE TITLE
Unit tests not passing.

### ISSUE THREAD

**Issue by PiotrJustyna** [forcedotcom/aura#177]
Executing:

```
mvn clean install
```

on Windows results in breaking unit tests:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.auraframework.util.json.JsonReaderTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.228 sec - in org.auraframework.util.json.JsonReaderTest
Running org.auraframework.util.AuraTextUtilTest
Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec - in org.auraframework.util.AuraTextUtilTest
Running org.auraframework.util.DirectoryCleanerTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.365 sec <<< FAILURE! - in org.auraframework.util.DirectoryCleanerTest
testDirectoryCleanerWithProtectedDirectory(org.auraframework.util.DirectoryCleanerTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.UnsupportedOperationException
        at org.auraframework.util.DirectoryCleanerTest.testDirectoryCleanerWithProtectedDirectory(DirectoryCleanerTest.java:73)

Running org.auraframework.util.IOUtilTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec <<< FAILURE! - in org.auraframework.util.IOUtilTest
testDelete(org.auraframework.util.IOUtilTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: test cleanup failed
        at org.auraframework.util.IOUtilTest.testDelete(IOUtilTest.java:88)

Running org.auraframework.util.javascript.directive.impl.DebuggerDirectiveTest
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.248 sec - in org.auraframework.util.javascript.directive.impl.DebuggerDirectiveTest
Running org.auraframework.util.json.JsonTest
136 [main] INFO org.reflections.Reflections - Reflections took 120 ms to scan 2 urls, producing 6 keys and 76 values
Tests run: 35, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.229 sec - in org.auraframework.util.json.JsonTest
Running org.auraframework.util.resource.CompiledGroupTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.resource.CompiledGroupTest
Running org.auraframework.util.javascript.JavascriptWriterTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.123 sec - in org.auraframework.util.javascript.JavascriptWriterTest
Running org.auraframework.util.javascript.directive.JavascriptGeneratorModeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.javascript.directive.JavascriptGeneratorModeTest
Running org.auraframework.util.json.JsFunctionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.auraframework.util.json.JsFunctionTest
Running org.auraframework.util.text.HashTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in org.auraframework.util.text.HashTest
Running org.auraframework.util.javascript.directive.impl.IfDirectiveTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.077 sec - in org.auraframework.util.javascript.directive.impl.IfDirectiveTest
Running org.auraframework.util.json.JsonStreamReaderTest
Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.193 sec - in org.auraframework.util.json.JsonStreamReaderTest
Running org.auraframework.util.javascript.directive.DirectiveParserTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec - in org.auraframework.util.javascript.directive.DirectiveParserTest
Running org.auraframework.util.javascript.directive.impl.IncludeDirectiveTest
ERROR: include directive unable to find: reallyconkyinclude
ERROR: include directive unable to find: haha.js
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in org.auraframework.util.javascript.directive.impl.IncludeDirectiveTest
Running org.auraframework.util.javascript.CommonJavascriptGroupImplTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.064 sec <<< FAILURE! - in org.auraframework.util.javascript.CommonJavascriptGroupImplTest
testBasicInitialization(org.auraframework.util.javascript.CommonJavascriptGroupImplTest)  Time elapsed: 0.004 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Addition of a valid javascript file failed
        at org.auraframework.util.javascript.CommonJavascriptGroupImplTest.testBasicInitialization(CommonJavascriptGroupImplTest.java:82)

Running org.auraframework.util.ServiceLocatorTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.035 sec - in org.auraframework.util.ServiceLocatorTest
Running org.auraframework.util.resource.ResourceLoaderTest
Tests run: 19, Failures: 2, Errors: 7, Skipped: 0, Time elapsed: 0.371 sec <<< FAILURE! - in org.auraframework.util.resource.ResourceLoaderTest
testGetResourceCachedMissingVersion(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusjem_15ewu8fh6h6no\testGetResourceCachedMissingVersion-ORIG
        at org.auraframework.util.resource.ResourceLoaderTest.createJarFromFolder(ResourceLoaderTest.java:536)
        at org.auraframework.util.resource.ResourceLoaderTest.createJarResourceLoader(ResourceLoaderTest.java:137)
        at org.auraframework.util.resource.ResourceLoaderTest.testGetResourceCachedMissingVersion(ResourceLoaderTest.java:428)

testGetResourceCachedMissingVersion(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.015 sec  <<< ERROR!
org.auraframework.util.IOUtil$DeleteFailedException: Failed to delete C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusjem_15ewu8fh6h6no\testGetResourceCachedMissingVersion.jar
        at org.auraframework.util.resource.ResourceLoaderTest.tearDown(ResourceLoaderTest.java:111)

testCacheDirParentNotWritable(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.015 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Should have failed to cache resource
        at org.auraframework.util.resource.ResourceLoaderTest.testCacheDirParentNotWritable(ResourceLoaderTest.java:250)

testCacheDirParentNotWritable(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.015 sec  <<< ERROR!
org.auraframework.util.IOUtil$DeleteFailedException: Failed to delete C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusjhm_9new2opi032h\testCacheDirParentNotWritable-TEMP\resourceCache\testCacheDirParentNotWritable4352177749160688220.tmp
        at org.auraframework.util.resource.ResourceLoaderTest.tearDown(ResourceLoaderTest.java:111)

testObstructedRecurisvely(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusji2_1wwpvd14lj6y7\testObstructedRecurisvely-ORIG
        at org.auraframework.util.resource.ResourceLoaderTest.createJarFromFolder(ResourceLoaderTest.java:536)
        at org.auraframework.util.resource.ResourceLoaderTest.createJarResourceLoader(ResourceLoaderTest.java:137)
        at org.auraframework.util.resource.ResourceLoaderTest.testObstructedRecurisvely(ResourceLoaderTest.java:479)

testObstructedRecurisvely(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.016 sec  <<< ERROR!
org.auraframework.util.IOUtil$DeleteFailedException: Failed to delete C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusji2_1wwpvd14lj6y7\testObstructedRecurisvely.jar
        at org.auraframework.util.resource.ResourceLoaderTest.tearDown(ResourceLoaderTest.java:111)

testCacheDirParentIsAFile(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.016 sec  <<< FAILURE!
junit.framework.AssertionFailedError
        at org.auraframework.util.resource.ResourceLoaderTest.testCacheDirParentIsAFile(ResourceLoaderTest.java:235)

testGetResourceNotCached(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusjjt_-ly4l9tmkvth6\testGetResourceNotCached-ORIG
        at org.auraframework.util.resource.ResourceLoaderTest.createJarFromFolder(ResourceLoaderTest.java:536)
        at org.auraframework.util.resource.ResourceLoaderTest.createJarResourceLoader(ResourceLoaderTest.java:137)
        at org.auraframework.util.resource.ResourceLoaderTest.testGetResourceNotCached(ResourceLoaderTest.java:285)

testGetResourceNotCached(org.auraframework.util.resource.ResourceLoaderTest)  Time elapsed: 0.013 sec  <<< ERROR!
org.auraframework.util.IOUtil$DeleteFailedException: Failed to delete C:\Users\piotr_justyna\AppData\Local\Temp\aura_jptusfek_-n7j6pape70pn\ResourceTest_jptusjjt_-ly4l9tmkvth6\testGetResourceNotCached.jar
        at org.auraframework.util.resource.ResourceLoaderTest.tearDown(ResourceLoaderTest.java:111)

Running org.auraframework.util.javascript.directive.JavascriptGeneratorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.auraframework.util.javascript.directive.JavascriptGeneratorTest
Running org.auraframework.util.javascript.directive.DirectiveBasedJavascriptGroupTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 1.024 sec - in org.auraframework.util.javascript.directive.DirectiveBasedJavascriptGroupTest
Running org.auraframework.util.javascript.directive.impl.DirectiveImplTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.javascript.directive.impl.DirectiveImplTest
Running org.auraframework.util.validation.ValidationErrorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.validation.ValidationErrorTest
Running org.auraframework.util.io.Utf8InputStreamReaderTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.io.Utf8InputStreamReaderTest
Running org.auraframework.util.io.LimitedLengthInputStreamTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.io.LimitedLengthInputStreamTest
Running org.auraframework.util.adapter.GitSourceControlAdapterTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.adapter.GitSourceControlAdapterTest
Running org.auraframework.util.date.DateServiceTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec - in org.auraframework.util.date.DateServiceTest
Running org.auraframework.util.javascript.MultiStreamReaderTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.javascript.MultiStreamReaderTest
Running org.auraframework.util.text.GlobMatcherTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.auraframework.util.text.GlobMatcherTest

Results :

Failed tests:
  IOUtilTest.testDelete:88 test cleanup failed
  CommonJavascriptGroupImplTest.testBasicInitialization:82 Addition of a valid javascript file failed
  ResourceLoaderTest.testCacheDirParentIsAFile:235
Tests in error:
  DirectoryCleanerTest.testDirectoryCleanerWithProtectedDirectory:73 ▒ UnsupportedOperation
org.auraframework.util.resource.ResourceLoaderTest.testCacheDirParentNotWritable(org.auraframework.util.resource.ResourceLoaderTest)
  Run 1: ResourceLoaderTest.testCacheDirParentNotWritable:250 Should have failed to cache resource
  Run 2: ResourceLoaderTest>UnitTestCase.legacyTearDown:110->tearDown:111 ▒ DeleteFailed

org.auraframework.util.resource.ResourceLoaderTest.testGetResourceCachedMissingVersion(org.auraframework.util.resource.ResourceLoaderTest)
  Run 1: ResourceLoaderTest.testGetResourceCachedMissingVersion:428->createJarResourceLoader:137->createJarFromFolder:536 ▒ URISyntax
  Run 2: ResourceLoaderTest>UnitTestCase.legacyTearDown:110->tearDown:111 ▒ DeleteFailed

org.auraframework.util.resource.ResourceLoaderTest.testGetResourceNotCached(org.auraframework.util.resource.ResourceLoaderTest)
  Run 1: ResourceLoaderTest.testGetResourceNotCached:285->createJarResourceLoader:137->createJarFromFolder:536 ▒ URISyntax
  Run 2: ResourceLoaderTest>UnitTestCase.legacyTearDown:110->tearDown:111 ▒ DeleteFailed

org.auraframework.util.resource.ResourceLoaderTest.testObstructedRecurisvely(org.auraframework.util.resource.ResourceLoaderTest)
  Run 1: ResourceLoaderTest.testObstructedRecurisvely:479->createJarResourceLoader:137->createJarFromFolder:536 ▒ URISyntax
  Run 2: ResourceLoaderTest>UnitTestCase.legacyTearDown:110->tearDown:111 ▒ DeleteFailed


Tests run: 231, Failures: 3, Errors: 5, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Aura Framework 0.6000-SNAPSHOT:
[INFO]
[INFO] Aura Framework ..................................... SUCCESS [ 10.214 s]
[INFO] aura-interfaces .................................... SUCCESS [  2.515 s]
[INFO] aura-spring ........................................ SUCCESS [  0.823 s]
[INFO] aura-util .......................................... FAILURE [ 12.640 s]
[INFO] aura ............................................... SKIPPED
[INFO] aura-impl-expression ............................... SKIPPED
[INFO] aura-impl .......................................... SKIPPED
[INFO] aura-tools ......................................... SKIPPED
[INFO] aura-components .................................... SKIPPED
[INFO] aura-modules ....................................... SKIPPED
[INFO] aura-resources ..................................... SKIPPED
[INFO] aura-integration-test .............................. SKIPPED
[INFO] aura-jetty ......................................... SKIPPED
[INFO] archetype for Aura-based "hello, world" ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.612 s
[INFO] Finished at: 2018-12-18T14:38:37Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project aura-util: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\piotr_justyna\git\aura\aura-util\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aura-util
```

**Comment by rahul-chaudhary** [comment]
for now as a workaround got to aura/pom.xml and change the property skipUnitTests from false to true
