### ISSUE TITLE
resource contention exception

### ISSUE THREAD

**Issue by jasonzhang2022** [forcedotcom/aura#34]
This is my first trial. The only modfication I did was changing the order of ulr-pattern and filter-name inside the filter-mapping since my eclipse complained the xml was not well-formatted. 

I got this error 

```
Problem accessing /aurodoc/docs.app. Reason:

    Server Error
Caused by:

org.auraframework.throwable.AuraRuntimeException: Namespace/Prefix combination markup://auratest claimed by 2 SourceLoaders : org.auraframework.impl.source.resource.ResourceSourceLoader and org.auraframework.impl.source.file.FileSourceLoader
    at org.auraframework.impl.source.SourceFactory.<init>(SourceFactory.java:76)
    at org.auraframework.impl.context.AuraRegistryProviderImpl.getRegistries(AuraRegistryProviderImpl.java:295)
    at org.auraframework.impl.context.AuraContextServiceImpl.getRegistries(AuraContextServiceImpl.java:149)
    at org.auraframework.impl.context.AuraContextServiceImpl.getDefRegistry(AuraContextServiceImpl.java:142)
    at org.auraframework.impl.context.AuraContextServiceImpl.startContext(AuraContextServiceImpl.java:111)
    at org.auraframework.impl.context.AuraContextServiceImpl.startContext(AuraContextServiceImpl.java:97)
    at org.auraframework.http.AuraContextFilter.startContext(AuraContextFilter.java:161)
    at org.auraframework.http.AuraContextFilter.doFilter(AuraContextFilter.java:105)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:276)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
    at org.auraframework.http.AuraRewriteFilter.doFilter(AuraRewriteFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jasonzhang2022** [comment]
I change the aura.framework.version to 0.1674 after I compare the generated project with this aura-note project. The project worted after this change.
